server:
  port: 8080
databases:
  - user: admin
    password: admin
    host: localhost
    database_name: shopDEV
  - user: admin
    password: admin
    host: localhost
    database_name: shopDEV2
security:
  jwt:
    key: secret
